sudo: required
services:
  - docker

before_install:
  - docker build -t jamdahl/docker-test-cicd -f Dockerfile.dev .

script:
  - docker run jamdahl/docker-test-cicd npm run test -- --coverage --forceExit